<?php if($theme_options->get( 'colors_status' ) == '1') { ?>
<style type="text/css">
	<?php if($theme_options->get( 'main_color' ) != '') { ?>
	a:hover,
	.mini-cart-info td.total,
	.mini-cart-total td:last-child,
	.product-list .name-desc .name a:hover,
	.product-filter .options .button-group button:hover,
	.product-filter .options .button-group .active,
	.with-arrow .box-content:before,
	.copyright .pattern a,
	.box .box-heading span,
	.col-sm-3 .box .box-heading,
	.col-sm-4 .box .box-heading,
	.col-md-3 .box .box-heading,
	.col-md-4 .box .box-heading,
	.center-column .box .box-heading,
	.box-category ul li a.active,
	.latest-news .overflow .title a:hover,
	.latest-news .overflow .readmore,
	.special-offers .product .name a:hover,
	.special-offers .product .price .price-new,
	.popup-newsletter .content span,
	.post .meta > li a,
	.posts .button-more,
	.mfilter-heading,
	.popup-newsletter .content span,
	.cart-total table tr td:last-child,
	.popup-newsletter .content span,
	.goshop-newsletter h4 span,
	#top-bar .dropdown:hover > a,
	#top-bar ul.menu li .main:hover,
	div.pagination-results ul li.active,
	.limited-time-offer .is-countdown .countdown-section .countdown-period,
	.found-your-dream .first-heading span,
	.roundabout .price,
	.product-grid .product .name a:hover,
	.product-grid .product .price,
	.product-list .price,
	.promotion .brand span,
	ul.megamenu > li > a:hover, ul.megamenu > li.active > a, ul.megamenu > li.home > a, ul.megamenu > li:hover > a,
	ul.megamenu li .sub-menu .content .static-menu a.main-menu:hover,
	.promotion2 .second-heading span,
	.promotion ul.actions li a:hover,
	.free-your-run .second-heading span {
		color: <?php echo $theme_options->get( 'main_color' ); ?>;
	}
		
	.button,
	.btn,
	body .popup-module .mfp-close:before,
	.tagcloud a,
	.news .media-body .tags a,
	.col-sm-3 .box .box-heading:before,
	.col-sm-4 .box .box-heading:before,
	.col-md-3 .box .box-heading:before,
	.col-md-4 .box .box-heading:before,
	.center-column .box .box-heading:before,
	.about-us .social-icons li a:hover,
	.latest-news .overflow .article-date-added,
	.testimonials .owl-pagination .owl-page.active,
	.latest-news .overflow .article-date-added,
	.post .tags a,
	.post .post-media .media-slider .owl-controls .owl-buttons .owl-prev:hover,
	.post .post-media .media-slider .owl-controls .owl-buttons .owl-next:hover,
	.post .post-media .media-slider .owl-controls .owl-buttons .owl-prev:hover,
	.post .post-media .media-slider .owl-controls .owl-buttons .owl-next:hover,
	.posts .post .tags a,
	.posts .button-more:hover,
	.mfilter-heading:before,
	#top-bar ul.menu li .main:hover span.cart-count,
	.testimonials .owl-pagination .owl-page.active,
	.featured-products .description,
	.sale,
	.product-grid .product .only-hover ul li a:hover,
	.product-grid .product .only-hover ul li:last-child a,
	ul.megamenu li .sub-menu .content .static-menu a.main-menu:before,
	.megamenuToogle-wrapper,
	.box-product .owl-pagination > div.active,
	.box2 .box-heading:before,
	.service .left:before {
		background-color: <?php echo $theme_options->get( 'main_color' ); ?>;
	}
	
	.posts .button-more:hover,
	.about-us .social-icons li a:hover,
	#top-bar ul.menu li .main:hover span.cart-count,
	.product-grid .only-hover,
	ul.megamenu > li > a:hover, ul.megamenu > li.active > a, ul.megamenu > li.home > a, ul.megamenu > li:hover > a {
		border-color: <?php echo $theme_options->get( 'main_color' ); ?>;
	}
	<?php } ?>
</style>
<?php } ?>